// <auto-generated />
using System;
using HoteleriaApp.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoteleriaApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330182609_ForzarBorradoIndicePiso")]
    partial class ForzarBorradoIndicePiso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("operacion");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("tabla");

                    b.HasKey("Id");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.BloqueoHabitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoBloqueo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("BloqueosHabitacion");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.CategoriaServicio", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_categoria");

                    b.Property<Guid>("IdServicio")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_servicio");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdCategoria", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("Categoria_Servicio", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_categoria");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Characteristics")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.DetalleReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_detalle");

                    b.Property<Guid>("IdHabitacion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_habitacion");

                    b.Property<Guid>("IdReserva")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva");

                    b.HasKey("Id");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdReserva");

                    b.ToTable("Detalle_Reserva", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Habitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_habitacion");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("numero");

                    b.Property<int>("Piso")
                        .HasColumnType("int")
                        .HasColumnName("piso");

                    b.Property<Guid>("TipoHabitacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tipo_habitacion_id");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.HabitacionAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("HabitacionesAmenities");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.HistorialEstadoReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_historial");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cambio");

                    b.Property<Guid>("IdReserva")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observacion");

                    b.HasKey("Id");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Historial_Estado_Reserva", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pago");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<Guid>("IdReserva")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("referencia_externa");

                    b.HasKey("Id");

                    b.HasIndex("IdReserva");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Piso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_piso");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroPiso")
                        .HasColumnType("int")
                        .HasColumnName("numero_piso");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPiso");

                    b.ToTable("Piso", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmada")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaEntrada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_categoria");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int>("NumeroHuespedes")
                        .HasColumnType("int")
                        .HasColumnName("numero_huespedes");

                    b.Property<string>("NumeroReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_reserva");

                    b.Property<decimal>("PrecioBaseNoche")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_base_noche");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referencia_externa");

                    b.Property<decimal>("SubtotalHabitacion")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal_habitacion");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<int>("TotalNoches")
                        .HasColumnType("int")
                        .HasColumnName("total_noches");

                    b.Property<decimal>("TotalServicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_servicios");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NumeroReserva")
                        .IsUnique();

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.ReservaHabitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservasHabitaciones");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.ReservaServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva_servicio");

                    b.Property<Guid>("IdReserva")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reserva");

                    b.Property<Guid>("IdServicio")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_servicio");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_aplicado");

                    b.HasKey("Id");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdReserva", "IdServicio")
                        .IsUnique();

                    b.ToTable("Reserva_Servicio", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_servicio");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Tarifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tarifa");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_categoria");

                    b.Property<Guid?>("IdTemporada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_temporada");

                    b.Property<decimal>("PrecioNoche")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_noche");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdTemporada");

                    b.ToTable("Tarifa", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_temporada");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Temporada", (string)null);
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacidadBase")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioBasePorNoche")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TiposHabitacion");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Email = "admin@hotel.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador del Sistema",
                            PasswordHash = "$2a$12$7VSbFVWWrwtu3w5UpUEkmuNnlrhxPWM1JIXslLB./qvp.1wAJh39K",
                            Rol = "Administrador"
                        });
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.BloqueoHabitacion", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany("Bloqueos")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.CategoriaServicio", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Category", "Categoria")
                        .WithMany("CategoriaServicios")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany("CategoriaServicios")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.DetalleReserva", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany("DetallesReserva")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Reserva", "Reserva")
                        .WithMany("DetallesReserva")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Habitacion", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Category", "Categoria")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.TipoHabitacion", "TipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.HabitacionAmenity", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Amenity", "Amenity")
                        .WithMany("Habitaciones")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany("Amenities")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.HistorialEstadoReserva", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Historial")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Pago", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Category", "Category")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.ReservaHabitacion", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Habitaciones")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.ReservaServicio", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Reserva", "Reserva")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Tarifa", b =>
                {
                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Category", "Categoria")
                        .WithMany("Tarifas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoteleriaApp.Core.Domain.Entities.Temporada", "Temporada")
                        .WithMany("Tarifas")
                        .HasForeignKey("IdTemporada")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("CategoriaServicios");

                    b.Navigation("Habitaciones");

                    b.Navigation("Reservas");

                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Habitacion", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bloqueos");

                    b.Navigation("DetallesReserva");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("DetallesReserva");

                    b.Navigation("Habitaciones");

                    b.Navigation("Historial");

                    b.Navigation("Pagos");

                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("CategoriaServicios");

                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Temporada", b =>
                {
                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("HoteleriaApp.Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
